// examples/var-angular/src/app/components/loop/loop.component.ts
import { KeyValue } from '@angular/common'
import { Component } from '@angular/core'

import { LoopItem } from '../../models/loop-item'

@Component({
  selector: 'app-loop',
  templateUrl: './loop.component.html',
  styleUrls: ['./loop.component.scss']
})
export class LoopComponent {
  arrayRef = Array
  items = [
    { id: 1, text: 'foo' },
    { id: 2, text: 'bar' },
    { id: 3, text: 'woo' }
  ]
  person = {
    name: 'Gordon',
    age: 18,
    power: 999,
    isSuper: true
  }

  trackById(index: number, item: LoopItem) {
    return item.id
  }

  trackByKey(index: number, item: KeyValue<string, any>) {
    return item.key
  }

  getItems(take: number) {
    return [
      { id: 4, text: 'foo' },
      { id: 5, text: 'bar' },
      { id: 6, text: 'woo' }
    ].slice(0, take)
  }
}

<h3>Array Rendering</h3>
<ul>
  <li *ngFor="let item of items; index as i; trackBy: trackById;">
    index: {{i}} | text: {{item.text}}
  </li>
</ul>
<hr>
<h3>Object Rendering `not directly built-in`</h3>
<ul>
  <li *ngFor="let item of person | keyvalue; index as i; trackBy: trackByKey;">
    index: {{i}} | name: {{item.key}} | value: {{item.value}}
  </li>
</ul>
<hr>
<h3>Times Rendering `not built-in`</h3>
<ul>
  <li *ngFor="let x of arrayRef.from(arrayRef(3).keys())">{{x + 1}}</li>
</ul>
<hr>
<h3>Characters Rendering `not built-in`</h3>
<ul>
  <li *ngFor="let c of 'Good'.split('')">{{c}}</li>
</ul>
<hr>
<h3>Alias</h3>
<ul>
  <li *ngFor="let item of items;
              index as i;
              count as c;
              first as isFirst;
              last as isLast;
              even as isEven;
              odd as isOdd;">
    index: {{i}} |
    count: {{c}} |
    first: {{isFirst}} |
    last: {{isLast}} |
    even: {{isEven}} |
    odd: {{isOdd}}
  </li>
</ul>
<hr>
<h3>Without Showing a Root Element</h3>
<ul>
  <ng-container *ngFor="let item of items; index as i; trackBy: trackById;">
    <li>index: {{i}}</li>
    <li>text: {{item.text}}</li>
  </ng-container>
</ul>
<hr>
<h3>With a Component</h3>
<ul>
  <app-loop-item *ngFor="let item of items; index as i; trackBy: trackById;"
                 [item]="item"
                 [index]="i"></app-loop-item>
</ul>
<hr>
<h3>With a Component & Without Showing a Root Element</h3>
<ul>
  <li appLoopItemAttr
      *ngFor="let item of items; index as i; trackBy: trackById;"
      [item]="item"
      [index]="i"></li>
</ul>
<hr>
<h3>Use Pipe to Get Rid of trackByFn</h3>
<ul>
  <li *ngFor="let item of items; index as i; trackBy: 'id' | trackByProperty">
    index: {{i}} | text: {{item.text}}
  </li>
</ul>
<hr>
<h3>With a Method</h3>
<ul>
  <li *ngFor="let item of getItems(3)">
    {{item.id}}
  </li>
</ul>

// examples/var-react/src/components/Loop.js
import LoopItem from './LoopItem'
import React from 'react'

function Loop() {
  const items = [
    { id: 1, text: 'foo' },
    { id: 2, text: 'bar' },
    { id: 3, text: 'woo' }
  ]
  const person = {
    name: 'Gordon',
    age: 18,
    power: 999,
    isSuper: true
  }
  const getItems = take => {
    return [
      { id: 4, text: 'foo' },
      { id: 5, text: 'bar' },
      { id: 6, text: 'woo' }
    ].slice(0, take)
  }

  return (
    <>
      <h3>Array Rendering</h3>
      <ul>
        {items.map((item, index) => {
          return (
            <li key={item.id}>
              index: {index} | text: {item.text}
            </li>
          )
        })}
      </ul>
      <hr />
      <h3>Object Rendering</h3>
      <ul>
        {Object.keys(person).map((key, index) => {
          return (
            <li key={key}>
              index: {index} | name: {key} | value: {person[key]}
            </li>
          )
        })}
      </ul>
      <hr />
      <h3>Times Rendering</h3>
      <ul>
        {Array.from(Array(3).keys()).map(x => {
          return <li key={x}>{x + 1}</li>
        })}
      </ul>
      <hr />
      <h3>Characters Rendering</h3>
      <ul>
        {'Good'.split('').map((c, index) => {
          return <li key={index}>{c}</li>
        })}
      </ul>
      <hr />
      <h3>Alias</h3>
      <ul>
        {items.map((item, index) => {
          const isFirst = index === 0
          const isLast = index === items.length - 1
          const isEven = index % 2 === 0
          const isOdd = index % 2 === 1
          return (
            <li key={item.id}>
              index: {index} |
              count: {items.length} |
              first: {isFirst.toString()} |
              last: {isLast.toString()} |
              even: {isEven.toString()} |
              odd: {isOdd.toString()}
            </li>
          )
        })}
      </ul>
      <hr />
      <h3>Without Showing a Root Element</h3>
      <ul>
        {items.map((item, index) => {
          return (
            <React.Fragment key={item.id}>
              <li>index: {index}</li>
              <li>text: {item.text}</li>
            </React.Fragment>
          )
        })}
      </ul>
      <hr />
      <h3>With a Component</h3>
      <ul>
        {items.map((item, index) => {
          return <LoopItem index={index} item={item} key={item.id} />
        })}
      </ul>
      <hr />
      <h3>With a Method</h3>
      <ul>
        {getItems(3).map((item, index) => {
          return <li key={item.id}>{item.id}</li>
        })}
      </ul>
    </>
  )
}

export default Loop
