// examples/var-angular/src/app/components/create-api/create-api.component.ts
import { HttpClient } from '@angular/common/http'
import { Component, ElementRef, ViewChild } from '@angular/core'

@Component({
  selector: 'app-create-api',
  templateUrl: './create-api.component.html',
  styleUrls: ['./create-api.component.scss']
})
export class CreateApiComponent {
  @ViewChild('name') nameRef: ElementRef
  @ViewChild('key') keyRef: ElementRef

  constructor(
    private http: HttpClient
  ) { }

  createSkill() {
    const newSkill = {
      name: this.nameRef.nativeElement.value,
      key: this.keyRef.nativeElement.value
    }
    this.http
      .post<{ message: string }>('http://localhost:4000/skill/', newSkill)
      .subscribe(
        data => alert(data.message),
        error => console.log(error)
      )
  }
}

<input type="text"
       #name />
<input type="text"
       #key />
<button (click)="createSkill()">Create</button>

// examples/var-vue/src/components/CreateApi.vue
<template>
  <div>
    <input type="text" ref="name" />
    <input type="text" ref="key" />
    <button @click="createSkill()">Create</button>
  </div>
</template>

<script>
import axios from 'axios'
export default {
  name: 'CreateApi',
  methods: {
    createSkill() {
      const newSkill = {
        name: this.$refs.name.value,
        key: this.$refs.key.value
      }
      axios
        .post('http://localhost:4000/skill/', newSkill)
        .then(response => alert(response.data.message))
        .catch(error => console.log(error))
    }
  }
}
</script>
