// examples/var-angular/src/app/components/detail-api/detail-api.component.ts
import { HttpClient } from '@angular/common/http'
import { Component, OnInit } from '@angular/core'

@Component({
  selector: 'app-detail-api',
  templateUrl: './detail-api.component.html',
  styleUrls: ['./detail-api.component.scss']
})
export class DetailApiComponent implements OnInit {
  skill = null

  constructor(
    private http: HttpClient
  ) { }

  ngOnInit(): void {
    const urlParams = new URLSearchParams(window.location.search)
    const id = urlParams.get('id') || 1
    this.detailSkill(id)
  }

  detailSkill(id) {
    this.http
      .get<any[]>('http://localhost:4000/skill/' + id)
      .subscribe(
        data => this.skill = data,
        error => console.log(error)
      )
  }
}

<div *ngIf="skill">
  {{skill.id}} -
  {{skill.name}}
  <span *ngIf="skill.key">[{{skill.key}}]</span>
</div>

// examples/var-vue/src/components/DetailApi.vue
<template>
  <div v-if="skill">
    {{skill.id}} -
    {{skill.name}}
    <span v-if="skill.key">[{{skill.key}}]</span>
  </div>
</template>

<script>
import axios from 'axios'
export default {
  name: 'DetailApi',
  data() {
    return {
      skill: null
    }
  },
  methods: {
    detailSkill(id) {
      axios
        .get('http://localhost:3000/skill/' + id)
        .then(response => (this.skill = response.data))
        .catch(error => console.log(error))
    }
  },
  mounted() {
    const urlParams = new URLSearchParams(window.location.search)
    const id = urlParams.get('id') || 1
    this.detailSkill(id)
  }
}
</script>
