// examples/var-angular/src/app/components/hero-props-parent/hero-props-parent.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-hero-props-parent',
  templateUrl: './hero-props-parent.component.html',
  styleUrls: ['./hero-props-parent.component.scss']
})
export class HeroPropsParentComponent {
  name = 'Riven'
  title = 'The Exile'
  health = 560
  attackDamage = 64
  skills = [
    { id: 1, name: 'Runic Blade', key: null },
    { id: 2, name: 'Broken Wings', key: 'q' },
    { id: 3, name: 'Ki Burst', key: 'w' },
    { id: 4, name: 'Valor', key: 'e' },
    { id: 5, name: 'Blade of the Exile', key: 'r' },
    { id: 6, name: 'Wind Slash', key: 'r' }
  ]
  isHighlight = true
}

<app-hero-props [name]="name"
                [title]="title"
                [health]="health"
                [attackDamage]="attackDamage"
                [skills]="skills"
                [attr.title]="'Super Hero'"
                [class.highlight]="isHighlight"
                [style.color]="isHighlight ? 'red' : 'green'"></app-hero-props>

// examples/var-vue/src/components/HeroPropsParent.vue
<template>
  <hero-props
    :name="name"
    :heroTitle="title"
    :health="health"
    :attackDamage="attackDamage"
    :skills="skills"
    :title="'Super' + ' Hero'"
    :class="isHighlight ? 'highlight' : null"
    :style="'color: red'"
  />
</template>

<script>
import HeroProps from './HeroProps'

export default {
  name: 'HeroPropsParent',
  data() {
    return {
      name: 'Riven',
      title: 'The Exile',
      health: 560,
      attackDamage: 64,
      skills: [
        { id: 1, name: 'Runic Blade', key: null },
        { id: 2, name: 'Broken Wings', key: 'q' },
        { id: 3, name: 'Ki Burst', key: 'w' },
        { id: 4, name: 'Valor', key: 'e' },
        { id: 5, name: 'Blade of the Exile', key: 'r' },
        { id: 6, name: 'Wind Slash', key: 'r' }
      ],
      isHighlight: true
    }
  },
  components: {
    HeroProps
  }
}
</script>
