// examples/var-angular/src/app/components/hero-state/hero-state.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-hero-state',
  templateUrl: './hero-state.component.html',
  styleUrls: ['./hero-state.component.scss']
})
export class HeroStateComponent {
  name = 'Riven'
  title = 'The Exile'
  health = 560
  attackDamage = 64
  skills = [
    { id: 1, name: 'Runic Blade', key: null },
    { id: 2, name: 'Broken Wings', key: 'q' },
    { id: 3, name: 'Ki Burst', key: 'w' },
    { id: 4, name: 'Valor', key: 'e' },
    { id: 5, name: 'Blade of the Exile', key: 'r' },
    { id: 6, name: 'Wind Slash', key: 'r' }
  ]
}

<h1>{{name}}</h1>
<h3>Health: {{health}}</h3>
<h3>Attack Damage: {{attackDamage}}</h3>
<ul>
  <li *ngFor="let skill of skills">
    {{skill.name}}
    <span *ngIf="skill.key">[{{skill.key}}]</span>
  </li>
</ul>

// examples/var-vue/src/components/HeroState.vue
<template>
  <div>
    <h1>{{description}}</h1>
    <h3>Health: {{health}}</h3>
    <h3>Attack Damage: {{attackDamage}}</h3>
    <ul>
      <li v-for="skill in skills" :key="skill.id">
        {{skill.name}}
        <span v-if="skill.key">[{{skill.key}}]</span>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: 'HeroState',
  data() {
    return {
      name: 'Riven',
      title: 'The Exile',
      health: 560,
      attackDamage: 64,
      skills: [
        { id: 1, name: 'Runic Blade', key: null },
        { id: 2, name: 'Broken Wings', key: 'q' },
        { id: 3, name: 'Ki Burst', key: 'w' },
        { id: 4, name: 'Valor', key: 'e' },
        { id: 5, name: 'Blade of the Exile', key: 'r' },
        { id: 6, name: 'Wind Slash', key: 'r' }
      ]
    }
  },
  computed: {
    description() {
      return this.name.toUpperCase() + ' - ' + this.title.toUpperCase()
    }
  }
}
</script>
