// examples/var-angular/src/app/components/hero-event-parent/hero-event-parent.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-hero-event-parent',
  templateUrl: './hero-event-parent.component.html',
  styleUrls: ['./hero-event-parent.component.scss']
})
export class HeroEventParentComponent {
  selectedItems = []
  skills = [
    { id: 1, name: 'Runic Blade' },
    { id: 2, name: 'Broken Wings' },
    { id: 3, name: 'Ki Burst' },
    { id: 4, name: 'Valor' },
    { id: 5, name: 'Blade of the Exile' },
    { id: 6, name: 'Wind Slash' }
  ]

  onSelectionChanges(selectedItems: any[]) {
    this.selectedItems = selectedItems
  }
}

<app-hero-event [items]="skills"
                (selectionChanges)="onSelectionChanges($event)"></app-hero-event>
<ol>
  <li *ngFor="let item of selectedItems">{{item.name + '\t'}}</li>
</ol>

// examples/var-vue/src/components/HeroEventParent.vue
<template>
  <div>
    <hero-event :items="skills" @selection-changes="onSelectionChanges($event)" />
    <ol>
      <li v-for="item in selectedItems" :key="item.id">{{item.name + '\t'}}</li>
    </ol>
  </div>
</template>

<script>
import HeroEvent from './HeroEvent'

export default {
  name: 'HeroEventParent',
  data() {
    return {
      selectedItems: [],
      skills: [
        { id: 1, name: 'Runic Blade' },
        { id: 2, name: 'Broken Wings' },
        { id: 3, name: 'Ki Burst' },
        { id: 4, name: 'Valor' },
        { id: 5, name: 'Blade of the Exile' },
        { id: 6, name: 'Wind Slash' }
      ]
    }
  },
  methods: {
    onSelectionChanges(selectedItems) {
      this.selectedItems = selectedItems
    }
  },
  components: {
    HeroEvent
  }
}
</script>
