// examples/var-angular/src/app/components/list-api/list-api.component.ts
import { HttpClient } from '@angular/common/http'
import { Component, OnInit } from '@angular/core'

@Component({
  selector: 'app-list-api',
  templateUrl: './list-api.component.html',
  styleUrls: ['./list-api.component.scss']
})
export class ListApiComponent implements OnInit {
  skills = []

  constructor(
    private http: HttpClient
  ) { }

  ngOnInit(): void {
    this.listSkills()
  }

  listSkills() {
    this.http
      .get<any[]>('http://localhost:4000/skill')
      .subscribe(
        data => this.skills = data,
        error => console.log(error)
      )
  }
}

<ul>
  <li *ngFor="let skill of skills">
    {{skill.name}}
    <span *ngIf="skill.key">[{{skill.key}}]</span>
  </li>
</ul>

// examples/var-vue/src/components/ListApi.vue
<template>
  <ul>
    <li v-for="skill in skills" :key="skill.id">
      {{skill.name}}
      <span v-if="skill.key">[{{skill.key}}]</span>
    </li>
  </ul>
</template>

<script>
import axios from 'axios'
export default {
  name: 'ListApi',
  data() {
    return {
      skills: []
    }
  },
  methods: {
    listSkills() {
      axios
        .get('http://localhost:3000/skill')
        .then(response => (this.skills = response.data))
        .catch(error => console.log(error))
    }
  },
  mounted() {
    this.listSkills()
  }
}
</script>
