// examples/var-angular/src/app/components/modify-api/modify-api.component.ts
import { HttpClient } from '@angular/common/http'
import { Component, ElementRef, ViewChild } from '@angular/core'

@Component({
  selector: 'app-modify-api',
  templateUrl: './modify-api.component.html',
  styleUrls: ['./modify-api.component.scss']
})
export class ModifyApiComponent {
  @ViewChild('id') idRef: ElementRef
  @ViewChild('name') nameRef: ElementRef
  @ViewChild('key') keyRef: ElementRef

  constructor(
    private http: HttpClient
  ) { }

  modifySkill() {
    const modifiedSkill = {
      name: this.nameRef.nativeElement.value,
      key: this.keyRef.nativeElement.value
    }
    this.http
      .put<{ message: string }>(
        'http://localhost:4000/skill/' + this.idRef.nativeElement.value,
        modifiedSkill
      )
      .subscribe(
        data => alert(data.message),
        error => console.log(error)
      )
  }
}

<input type="text"
       #id />
<input type="text"
       #name />
<input type="text"
       #key />
<button (click)="modifySkill()">Modify</button>

// examples/var-vue/src/components/ModifyApi.vue
<template>
  <div>
    <input type="text" ref="id" />
    <input type="text" ref="name" />
    <input type="text" ref="key" />
    <button @click="modifySkill()">Modify</button>
  </div>
</template>

<script>
import axios from 'axios'
export default {
  name: 'ModifyApi',
  methods: {
    modifySkill() {
      const modifiedSkill = {
        name: this.$refs.name.value,
        key: this.$refs.key.value
      }
      axios
        .put(
          'http://localhost:4000/skill/' + this.$refs.id.value,
          modifiedSkill
        )
        .then(response => alert(response.data.message))
        .catch(error => console.log(error))
    }
  }
}
</script>
