// examples/var-angular/src/app/components/remove-api/remove-api.component.ts
import { HttpClient } from '@angular/common/http'
import { Component, ElementRef, ViewChild } from '@angular/core'

@Component({
  selector: 'app-remove-api',
  templateUrl: './remove-api.component.html',
  styleUrls: ['./remove-api.component.scss']
})
export class RemoveApiComponent {
  @ViewChild('id') idRef: ElementRef

  constructor(
    private http: HttpClient
  ) { }

  removeSkill() {
    this.http
      .delete<{ message: string }>('http://localhost:4000/skill/' + this.idRef.nativeElement.value)
      .subscribe(
        data => alert(data.message),
        error => console.log(error)
      )
  }
}

<input type="text"
       #id />
<button (click)="removeSkill()">Remove</button>

// examples/var-vue/src/components/RemoveApi.vue
<template>
  <div>
    <input type="text" ref="id" />
    <button @click="removeSkill()">Remove</button>
  </div>
</template>

<script>
import axios from 'axios'
export default {
  name: 'RemoveApi',
  methods: {
    removeSkill() {
      axios
        .delete('http://localhost:3000/skill/' + this.$refs.id.value)
        .then(response => alert(response.data.message))
        .catch(error => console.log(error))
    }
  }
}
</script>
