// examples/var-vue/src/components/HeroEvent.vue
<template>
  <div>
    <ul>
      <li @click="toggleSelectAll()">
        <span v-if="isSelectedAll">☑</span>
        <span v-if="!isSelectedAll">☐</span>
        <strong>Select All</strong>
      </li>
      <li v-for="item in items" :key="item.id" @click="toggleSelectItem(item)">
        <span v-if="item.isSelected">☑</span>
        <span v-if="!item.isSelected">☐</span>
        {{item.name}}
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: 'HeroEvent',
  props: {
    skills: Array
  },
  data() {
    return {
      isSelectedAll: false
    }
  },
  computed: {
    items() {
      return this.skills.map(x => ({ ...x, isSelected: false }))
    }
  },
  methods: {
    onSelectionsChanged() {
      const selectedItems = this.items.filter(x => x.isSelected)
      this.$emit('selection-changes', selectedItems)
    },
    toggleSelectAll() {
      this.isSelectedAll = !this.isSelectedAll
      for (const item of this.items) {
        item.isSelected = this.isSelectedAll
      }
      this.onSelectionsChanged()
    },
    toggleSelectItem(item) {
      item.isSelected = !item.isSelected
      this.isSelectedAll = this.items.every(x => x.isSelected)
      this.onSelectionsChanged()
    }
  }
}
</script>

// examples/var-angular/src/app/components/hero-event/hero-event.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core'

@Component({
  selector: 'app-hero-event',
  templateUrl: './hero-event.component.html',
  styleUrls: ['./hero-event.component.scss']
})
export class HeroEventComponent {
  @Output() selectionChanges = new EventEmitter<any[]>()
  @Input() items: any[]
  isSelectedAll = false

  onSelectionsChanged() {
    const selectedItems = this.items.filter(x => x.isSelected)
    this.selectionChanges.emit(selectedItems)
  }

  toggleSelectAll() {
    this.isSelectedAll = !this.isSelectedAll
    for (const item of this.items) {
      item.isSelected = this.isSelectedAll
    }
    this.onSelectionsChanged()
  }

  toggleSelectItem(item) {
    item.isSelected = !item.isSelected
    this.isSelectedAll = this.items.every(x => x.isSelected)
    this.onSelectionsChanged()
  }
}

<ul>
  <li (click)="toggleSelectAll()">
    <span *ngIf="isSelectedAll">☑</span>
    <span *ngIf="!isSelectedAll">☐</span>
    <strong>Select All</strong>
  </li>
  <li *ngFor="let item of items"
      (click)="toggleSelectItem(item)">
    <span *ngIf="item.isSelected">☑</span>
    <span *ngIf="!item.isSelected">☐</span>
    {{item.name}}
  </li>
</ul>
