// examples/var-react/src/components/Event.js
import React, { useRef, useState } from 'react'

function Event() {
  const [val, setVal] = useState(10)
  const userInput = useRef()

  function addVal() {
    setVal(val + (Number(userInput.current.value) || 0))
  }

  function addWithVal(_val) {
    setVal(val + (Number(_val) || 0))
  }

  function hi(event) {
    alert(`${event.type} event`)
  }

  function foo(event, memo) {
    console.log(event.currentTarget, memo)
  }

  return (
    <>
      {val}
      <input type="text" ref={userInput} />
      <p>With Handler Reference</p>
      <button onClick={addVal}>Add Value</button>
      <p>With Invoking Handler</p>
      <button onClick={() => addVal()}>Add Value</button>
      <p>With a Expression</p>
      <button onClick={() => setVal(val + (Number(userInput.current.value) || 0))}>Add Value</button>
      <p>With Parameters</p>
      <button onClick={() => addWithVal(userInput.current.value)}>Add Value</button>
      <p>With the Event Parameter</p>
      <button onClick={hi}>Hi</button>
      <button onClick={event => hi(event)}>Hi</button>
    </>
  )
}

export default Event

// examples/var-angular/src/app/components/event/event.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core'

@Component({
  selector: 'app-event',
  templateUrl: './event.component.html',
  styleUrls: ['./event.component.scss']
})
export class EventComponent {
  @ViewChild('userInput') userInputRef: ElementRef

  val = 10
  number = Number

  addVal() {
    this.val += Number(this.userInputRef.nativeElement.value) || 0
  }

  addWithVal(val: string) {
    this.val += Number(val) || 0
  }

  hi(event: Event) {
    alert(`${event.type} event`)
  }

  foo(event: Event, memo: string = null) {
    console.log(event.currentTarget, memo)
  }
}

{{val}}
<input type="text"
       #userInput />
<p>With Invoking Handler</p>
<button (click)="addVal()">Add Value</button>
<p>With a Expression</p>
<button (click)="val = val + (number(userInput.value) || 0)">Add Value</button>
<p>With Parameters</p>
<button (click)="addWithVal(userInput.value)">Add Value</button>
<p>With the Event Parameter</p>
<button (click)="hi($event)">Hi</button>
<p>With the Event Filtering</p>
<input (keyup.enter)="hi($event)">
